### ISSUE TITLE
Design proposal

### ISSUE THREAD

**Issue by ritalinn** [techgaun/mock#4]
I like to help open source projects. I offer you a logo to help. Do you want to ?

**Comment by techgaun** [comment]
@ritalinn thanks! This is really a fork only and I am just adding stuff quickly for my needs. Do you want to create a logo for https://github.com/techgaun/ex_mustang though?

**Comment by ritalinn** [comment]
Of course. Do you mind if I open an issue there?

**Comment by techgaun** [comment]
go for it @ritalinn

**Comment by techgaun** [comment]
closing this one though
